services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    restart: unless-stopped
    networks:
      - general
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - general

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - general
    depends_on:
      - prometheus
    volumes:
      - ./grafana/runtime-data:/var/lib/grafana
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml

volumes:
  postgres_data:

networks:
  general:
    driver: bridge
